Update build123d to 0.9.0
Update to latest released version. This fixes the following exception for me: 
AttributeError: 'OCP.OCP.TopoDS.TopoDS_Shape' object has no attribute 'HashCode'